version: "3.8"
services:
  client:
    # image: dev-i
    build:
      # context: contextPath
      dockerfile: Dockerfile.dev
    container_name: dev-container
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development


volumes:
  node_modules:
    