version: "3.8"
services:
  client:
    image: prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: dev-container
    ports:
      - 8000:80
    environment:
      - NODE_ENV=production

    